### PR TITLE
Solving Issue#43

### PR DESCRIPTION
**Pull request by j0rt3g4**
Solving Issue #43

### CODE REVIEW

**Comment by j0rt3g4** [comment]
@scanum PR #44

**Comment by scanum** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by scanum** [comment]
@efrene Hi Efren, Changes look correct. Could you please review and merge? Thanks!

**Comment by efrene** [comment]
Will do! Thanks!
Efren

**Comment by scanum** [comment]
@efrene Hi Efren! Any updates on this? Thanks!

**Comment by efrene** [comment]
Sorry for the delay in approving this.  Thanks so much!

**Pull request merged**
