### PR TITLE
Updating maximum tasks limit

### PR DESCRIPTION
**Pull request by muralidhar-koduvande**
Updating the maximum task limits to 1000 from 500 in a project
We implemented this feature in the product and it is generally available now.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by muralidhar-koduvande** [comment]
@JohanFreelancer9 Can you please help in merging this pull request?

**Comment by JohanFreelancer9** [comment]
> @JohanFreelancer9 Can you please help in merging this pull request?

@scanum, can you please assist? Thanks.

**Comment by muralidhar-koduvande** [comment]
@scanum - Can you please merge this request?
This feature is rolled out and we need to update the documentation

**Comment by scanum** [comment]
Hi @muralidhar-koduvande hope all is well. I don't have permissions to merge. Adding @tiburd for guidance! Thanks.

**Pull request merged**
